/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myBank.view.login;

import java.awt.Color;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import static java.awt.Frame.NORMAL;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import myBank.controller.LoginController;

/**
 *
 * @author Fauzi
 */
public class loginFrame extends javax.swing.JFrame {
    LoginController loginCtrl = new LoginController();
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    private final double widthScreen = screenSize.getWidth();
    private final double heightScreen = screenSize.getHeight();
    private int modeScreen = 1;
    private int xMouse;
    private int yMouse;
    private int locationX;
    private int locationY;

    /**
     * Creates new form loginFrame
     */
    public loginFrame() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        pesanValidasiLabel.setVisible(false);
    }

    public void setMessageValidasi(String pesan, boolean set) {
        pesanValidasiLabel.setText(pesan);
        pesanValidasiLabel.setVisible(set);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barPanel = new javax.swing.JPanel();
        closeBtn = new javax.swing.JLabel();
        fullOrNormalSSBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        signInBtn = new javax.swing.JLabel();
        idUserTextField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        pesanValidasiLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 550));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(850, 550));

        barPanel.setBackground(new java.awt.Color(32, 103, 178));
        barPanel.setPreferredSize(new java.awt.Dimension(902, 30));
        barPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barPanelMouseDragged(evt);
            }
        });
        barPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barPanelMousePressed(evt);
            }
        });

        closeBtn.setBackground(new java.awt.Color(32, 103, 178));
        closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/close_screen_20px.png"))); // NOI18N
        closeBtn.setOpaque(true);
        closeBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        closeBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeBtnMouseMoved(evt);
            }
        });
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeBtnMouseReleased(evt);
            }
        });

        fullOrNormalSSBtn.setBackground(new java.awt.Color(32, 103, 178));
        fullOrNormalSSBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullOrNormalSSBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/normal_screen_20px.png"))); // NOI18N
        fullOrNormalSSBtn.setOpaque(true);
        fullOrNormalSSBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        fullOrNormalSSBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fullOrNormalSSBtnMouseMoved(evt);
            }
        });
        fullOrNormalSSBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullOrNormalSSBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullOrNormalSSBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fullOrNormalSSBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fullOrNormalSSBtnMouseReleased(evt);
            }
        });

        minimizeBtn.setBackground(new java.awt.Color(32, 103, 178));
        minimizeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/minimize_Screen_20px.png"))); // NOI18N
        minimizeBtn.setOpaque(true);
        minimizeBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        minimizeBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseMoved(evt);
            }
        });
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizeBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout barPanelLayout = new javax.swing.GroupLayout(barPanel);
        barPanel.setLayout(barPanelLayout);
        barPanelLayout.setHorizontalGroup(
            barPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barPanelLayout.createSequentialGroup()
                .addGap(0, 800, Short.MAX_VALUE)
                .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullOrNormalSSBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barPanelLayout.setVerticalGroup(
            barPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fullOrNormalSSBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(minimizeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(barPanel, java.awt.BorderLayout.PAGE_START);

        contentPanel.setBackground(new java.awt.Color(32, 103, 178));
        contentPanel.setLayout(new java.awt.GridLayout(1, 2));

        jPanel5.setBackground(new java.awt.Color(32, 103, 178));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        loginPanel.setBackground(new java.awt.Color(32, 103, 178));
        loginPanel.setPreferredSize(new java.awt.Dimension(350, 350));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGIN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        signInBtn.setBackground(new java.awt.Color(35, 171, 226));
        signInBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signInBtn.setForeground(new java.awt.Color(255, 255, 255));
        signInBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        signInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/login_30px.png"))); // NOI18N
        signInBtn.setText("Sign In");
        signInBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signInBtn.setOpaque(true);
        signInBtn.setPreferredSize(new java.awt.Dimension(65, 40));
        signInBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                signInBtnMouseMoved(evt);
            }
        });
        signInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signInBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signInBtnMouseReleased(evt);
            }
        });

        idUserTextField.setBackground(new java.awt.Color(32, 103, 178));
        idUserTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idUserTextField.setForeground(new java.awt.Color(255, 255, 255));
        idUserTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        idUserTextField.setPreferredSize(new java.awt.Dimension(0, 40));

        PasswordField.setBackground(new java.awt.Color(32, 103, 178));
        PasswordField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        PasswordField.setPreferredSize(new java.awt.Dimension(0, 40));

        pesanValidasiLabel.setForeground(new java.awt.Color(255, 255, 255));
        pesanValidasiLabel.setText("pesan validasi");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idUserTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(signInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesanValidasiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesanValidasiLabel))
                .addContainerGap())
        );

        jPanel5.add(loginPanel, new java.awt.GridBagConstraints());

        contentPanel.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(32, 103, 178));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        logoPanel.setBackground(new java.awt.Color(32, 103, 178));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/image/logoMyBank.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/image/namaBank.PNG"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/image/mottoBank.PNG"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        jPanel6.add(logoPanel, new java.awt.GridBagConstraints());

        contentPanel.add(jPanel6);

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(32, 103, 178));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        jPanel3.setPreferredSize(new java.awt.Dimension(5, 5));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(32, 103, 178));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(5, 5));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(32, 103, 178));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        jPanel4.setPreferredSize(new java.awt.Dimension(5, 5));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMouseExited
        signInBtn.setBorder(null);
    }//GEN-LAST:event_signInBtnMouseExited

    private void signInBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMouseMoved
        signInBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_signInBtnMouseMoved

    private void signInBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMousePressed
        signInBtn.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_signInBtnMousePressed

    private void signInBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMouseReleased
        signInBtn.setBackground(new Color(35, 171, 226));
    }//GEN-LAST:event_signInBtnMouseReleased

    private void closeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMousePressed
        closeBtn.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_closeBtnMousePressed

    private void fullOrNormalSSBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullOrNormalSSBtnMousePressed
        fullOrNormalSSBtn.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_fullOrNormalSSBtnMousePressed

    private void minimizeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMousePressed
        minimizeBtn.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_minimizeBtnMousePressed

    private void minimizeBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseReleased
        minimizeBtn.setBackground(new Color(35, 171, 226));
    }//GEN-LAST:event_minimizeBtnMouseReleased

    private void fullOrNormalSSBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullOrNormalSSBtnMouseReleased
        fullOrNormalSSBtn.setBackground(new Color(35, 171, 226));
    }//GEN-LAST:event_fullOrNormalSSBtnMouseReleased

    private void closeBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseReleased
        closeBtn.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_closeBtnMouseReleased

    private void closeBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseMoved
        closeBtn.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_closeBtnMouseMoved

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        closeBtn.setBackground(new Color(32, 103, 178));
    }//GEN-LAST:event_closeBtnMouseExited

    private void fullOrNormalSSBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullOrNormalSSBtnMouseExited
        fullOrNormalSSBtn.setBackground(new Color(32, 103, 178));
    }//GEN-LAST:event_fullOrNormalSSBtnMouseExited

    private void minimizeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseExited
        minimizeBtn.setBackground(new Color(32, 103, 178));
    }//GEN-LAST:event_minimizeBtnMouseExited

    private void minimizeBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseMoved
        minimizeBtn.setBackground(new Color(35, 171, 226));
    }//GEN-LAST:event_minimizeBtnMouseMoved

    private void fullOrNormalSSBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullOrNormalSSBtnMouseMoved
        fullOrNormalSSBtn.setBackground(new Color(35, 171, 226));
    }//GEN-LAST:event_fullOrNormalSSBtnMouseMoved

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void fullOrNormalSSBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullOrNormalSSBtnMouseClicked
        if (modeScreen == 1) {
            this.setExtendedState(NORMAL);
            this.setSize(850, 550);
            modeScreen = 0;
            fullOrNormalSSBtn.setIcon(new ImageIcon("src/mybank/resource/icon/full_screen_20px.PNG"));
            this.setLocationRelativeTo(null);
        } else {
            this.setExtendedState(MAXIMIZED_BOTH);
            modeScreen = 1;
            fullOrNormalSSBtn.setIcon(new ImageIcon("src/mybank/resource/icon/normal_screen_20px.PNG"));
        }
    }//GEN-LAST:event_fullOrNormalSSBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setExtendedState(ICONIFIED);
        modeScreen = 0;
        fullOrNormalSSBtn.setIcon(new ImageIcon("src/mybank/resource/icon/full_screen_20px.PNG"));
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void barPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barPanelMousePressed

    private void barPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setExtendedState(NORMAL);
        modeScreen = 0;
        fullOrNormalSSBtn.setIcon(new ImageIcon("src/mybank/resource/icon/full_screen_20px.PNG"));
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barPanelMouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        locationX = this.getLocationOnScreen().x;
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        locationY = this.getLocationOnScreen().y;
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        locationX = this.getLocationOnScreen().x;
        locationY = this.getLocationOnScreen().y;
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int widthFrame = evt.getXOnScreen();
        this.setSize(widthFrame - locationX, this.getContentPane().getHeight());
        if (widthFrame < widthScreen) {
            this.setExtendedState(NORMAL);
            modeScreen = 0;
            fullOrNormalSSBtn.setIcon(new ImageIcon("src/mybank/resource/icon/full_screen_20px.PNG"));
        } else {
            this.setExtendedState(MAXIMIZED_BOTH);
            modeScreen = 1;
            fullOrNormalSSBtn.setIcon(new ImageIcon("src/mybank/resource/icon/normal_screen_20px.PNG"));
        }
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int heightFrame = evt.getYOnScreen();
        this.setSize(this.getContentPane().getWidth(), heightFrame - locationY);
        if (heightFrame < heightScreen) {
            this.setExtendedState(NORMAL);
            modeScreen = 0;
            fullOrNormalSSBtn.setIcon(new ImageIcon("src/mybank/resource/icon/full_screen_20px.PNG"));
        } else {
            this.setExtendedState(MAXIMIZED_BOTH);
            modeScreen = 1;
            fullOrNormalSSBtn.setIcon(new ImageIcon("src/mybank/resource/icon/normal_screen_20px.PNG"));
        }
    }//GEN-LAST:event_jPanel2MouseDragged

    private void signInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMouseClicked
        loginCtrl.login(this);
    }//GEN-LAST:event_signInBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPanel barPanel;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel fullOrNormalSSBtn;
    private javax.swing.JTextField idUserTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel pesanValidasiLabel;
    private javax.swing.JLabel signInBtn;
    // End of variables declaration//GEN-END:variables

    public JPasswordField getPassword() {
        return PasswordField;
    }

    public JTextField getIdUser() {
        return idUserTextField;
    }
}
