/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myBank.view.manager.pegawai;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import myBank.controller.pegawaiController;
import myBank.style.buttonStyle;
import myBank.style.photoStyle;

/**
 *
 * @author Fauzi
 */
public class PegawaiNew extends javax.swing.JDialog {
    ButtonGroup radioGroup = new ButtonGroup();
    pegawaiController pegawaiCtrl = new pegawaiController();
    buttonStyle btnStyle = new buttonStyle();
    photoStyle photoStyle = new photoStyle();
    private String pathPhoto = "null";
    private String tglLahir ="";
    private PegawaiPanel pegawaipanel;
    /**
     * Creates new form pegawaiNew
     */
    public PegawaiNew(java.awt.Frame parent, boolean modal,PegawaiPanel pegawaipanel) {
        super(parent, modal);
        initComponents();
        this.pegawaipanel = pegawaipanel;
        radioGroup.add(jkLakiLakiRadioButton);
        radioGroup.add(jkPremepuanRadioButton);
        tanggalLahirDate.setDateFormatString("yyyy-MM-dd");
        jkLakiLakiRadioButton.setSelected(true);
        validasiPesanLabel.setVisible(false);
        this.setLocationRelativeTo(null);
    }
    public PegawaiNew(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        radioGroup.add(jkLakiLakiRadioButton);
        radioGroup.add(jkPremepuanRadioButton);
        tanggalLahirDate.setDateFormatString("yyyy-MM-dd");
        jkLakiLakiRadioButton.setSelected(true);
        validasiPesanLabel.setVisible(false);
        this.setLocationRelativeTo(null);
    }
    public void refreshPegawaiTable(){
        pegawaipanel.loadPegawaiTable();
    }
    public void setValidasi(String pesan, boolean stts) {
        validasiPesanLabel.setText(pesan);
        validasiPesanLabel.setVisible(stts);
    }
    public JTextField getNoKtp() {
        return noKtpTextField;
    }
    public JTextField getNama(){
        return namaLengkapTextField;
    }
    public JRadioButton getJkLakiLaki(){
        return jkLakiLakiRadioButton;
    }
    public JRadioButton getJkPerempuan(){
        return jkPremepuanRadioButton;
    }
    public JTextField getTempatLahir(){
        return tempatLahirTextFiled;
    }
    public String getTglLahir(){
        return tglLahir;
    }
    public JTextArea getAlamat(){
        return alamatTextArea;
    }
    public JTextField getNoTlp(){
        return noTlpTextField;
    }
    public JComboBox getJabatan(){
        return JabatanComboBox;
    }
    public String getPahtPhoto(){
        return pathPhoto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        slide1Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        noKtpTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        namaLengkapTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jkLakiLakiRadioButton = new javax.swing.JRadioButton();
        jkPremepuanRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        tempatLahirTextFiled = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tanggalLahirDate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        noTlpTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JabatanComboBox = new javax.swing.JComboBox();
        potoLabel = new javax.swing.JLabel();
        potoBtn = new javax.swing.JLabel();
        potoCancleBtn = new javax.swing.JLabel();
        validasiPesanLabel = new javax.swing.JLabel();
        simpanBtn = new javax.swing.JLabel();
        slide2Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 630));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(750, 630));

        jPanel1.setBackground(new java.awt.Color(32, 103, 178));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PEGAWAI BARU");

        closeBtn.setBackground(new java.awt.Color(32, 103, 178));
        closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/close_screen_20px.png"))); // NOI18N
        closeBtn.setOpaque(true);
        closeBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeBtnMouseMoved(evt);
            }
        });
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 451, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(closeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.CardLayout());

        slide1Panel.setBackground(new java.awt.Color(32, 103, 178));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No KTP");

        noKtpTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noKtpTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Lengkap");

        namaLengkapTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaLengkapTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis Kelamin");

        jkLakiLakiRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jkLakiLakiRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        jkLakiLakiRadioButton.setText("Laki - laki");
        jkLakiLakiRadioButton.setOpaque(false);

        jkPremepuanRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jkPremepuanRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        jkPremepuanRadioButton.setText("Perempuan");
        jkPremepuanRadioButton.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tempat Lahir");

        tempatLahirTextFiled.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tempatLahirTextFiled.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal Lahir");

        tanggalLahirDate.setBackground(new java.awt.Color(255, 255, 255));
        tanggalLahirDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalLahirDatePropertyChange(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No Telepon");

        noTlpTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noTlpTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        alamatTextArea.setColumns(20);
        alamatTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alamatTextArea.setLineWrap(true);
        alamatTextArea.setRows(5);
        jScrollPane1.setViewportView(alamatTextArea);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Alamat");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jabatan");

        JabatanComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MANAGER", "CS", "TELLER" }));

        potoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        potoLabel.setForeground(new java.awt.Color(255, 255, 255));
        potoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/user_100px.png"))); // NOI18N
        potoLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        potoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        potoLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        potoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        potoBtn.setBackground(new java.awt.Color(35, 171, 226));
        potoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/cari_30px.png"))); // NOI18N
        potoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        potoBtn.setOpaque(true);
        potoBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                potoBtnMouseMoved(evt);
            }
        });
        potoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potoBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                potoBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                potoBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                potoBtnMouseReleased(evt);
            }
        });

        potoCancleBtn.setBackground(new java.awt.Color(35, 171, 226));
        potoCancleBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potoCancleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/cancle_30px.png"))); // NOI18N
        potoCancleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        potoCancleBtn.setOpaque(true);
        potoCancleBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                potoCancleBtnMouseMoved(evt);
            }
        });
        potoCancleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potoCancleBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                potoCancleBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                potoCancleBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                potoCancleBtnMouseReleased(evt);
            }
        });

        validasiPesanLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        validasiPesanLabel.setForeground(new java.awt.Color(255, 255, 255));
        validasiPesanLabel.setText("*Pesan Validasi");
        validasiPesanLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Catatan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        simpanBtn.setBackground(new java.awt.Color(35, 171, 226));
        simpanBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        simpanBtn.setForeground(new java.awt.Color(255, 255, 255));
        simpanBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simpanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/Save_30px.png"))); // NOI18N
        simpanBtn.setText("SIMPAN");
        simpanBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanBtn.setOpaque(true);
        simpanBtn.setPreferredSize(new java.awt.Dimension(34, 40));
        simpanBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                simpanBtnMouseMoved(evt);
            }
        });
        simpanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                simpanBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                simpanBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                simpanBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout slide1PanelLayout = new javax.swing.GroupLayout(slide1Panel);
        slide1Panel.setLayout(slide1PanelLayout);
        slide1PanelLayout.setHorizontalGroup(
            slide1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slide1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(slide1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(slide1PanelLayout.createSequentialGroup()
                        .addGroup(slide1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(slide1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(slide1PanelLayout.createSequentialGroup()
                                    .addComponent(jkLakiLakiRadioButton)
                                    .addGap(79, 79, 79)
                                    .addComponent(jkPremepuanRadioButton))
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noKtpTextField)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namaLengkapTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tempatLahirTextFiled, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tanggalLahirDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 149, Short.MAX_VALUE)
                        .addGroup(slide1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(slide1PanelLayout.createSequentialGroup()
                                .addComponent(potoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(potoCancleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(potoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83))
                    .addGroup(slide1PanelLayout.createSequentialGroup()
                        .addGroup(slide1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(slide1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JabatanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noTlpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)))
                        .addGroup(slide1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(slide1PanelLayout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(simpanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(slide1PanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(validasiPesanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        slide1PanelLayout.setVerticalGroup(
            slide1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slide1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(slide1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(slide1PanelLayout.createSequentialGroup()
                        .addComponent(noKtpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaLengkapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(slide1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jkLakiLakiRadioButton)
                            .addComponent(jkPremepuanRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addComponent(potoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(slide1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(slide1PanelLayout.createSequentialGroup()
                        .addComponent(tempatLahirTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(potoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(potoCancleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalLahirDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(slide1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(slide1PanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noTlpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JabatanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(slide1PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(validasiPesanLabel)
                        .addGap(29, 29, 29)
                        .addComponent(simpanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3.add(slide1Panel, "card2");

        javax.swing.GroupLayout slide2PanelLayout = new javax.swing.GroupLayout(slide2Panel);
        slide2Panel.setLayout(slide2PanelLayout);
        slide2PanelLayout.setHorizontalGroup(
            slide2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        slide2PanelLayout.setVerticalGroup(
            slide2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        jPanel3.add(slide2Panel, "card3");

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void potoBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMouseMoved
        btnStyle.borderMouseMoved(potoBtn);
    }//GEN-LAST:event_potoBtnMouseMoved

    private void potoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMouseClicked
        JFileChooser jfc = new JFileChooser();
        FileFilter pngFilter = new FileNameExtensionFilter("photo (.png)", "png");
        jfc.setAcceptAllFileFilterUsed(false);
        jfc.addChoosableFileFilter(pngFilter);
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            pathPhoto = jfc.getSelectedFile().toString();
            if (!"".equals(pathPhoto)) {
                pathPhoto = pathPhoto.replace("\\", "/");
                BufferedImage loadImg = photoStyle.loadImage(pathPhoto);
                ImageIcon imageIcon = new ImageIcon(photoStyle.resize(loadImg, potoLabel.getWidth() - 1, potoLabel.getHeight() - 1));
                potoLabel.setIcon(imageIcon);
            }
        }
    }//GEN-LAST:event_potoBtnMouseClicked

    private void potoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMouseExited
        btnStyle.borderMouseExit(potoBtn);
    }//GEN-LAST:event_potoBtnMouseExited

    private void potoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMousePressed
        btnStyle.backgroundMousePressed(potoBtn);
    }//GEN-LAST:event_potoBtnMousePressed

    private void potoBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMouseReleased
        btnStyle.backgroundMouseReleased(potoBtn);
    }//GEN-LAST:event_potoBtnMouseReleased

    private void potoCancleBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMouseMoved
        btnStyle.borderMouseMoved(potoCancleBtn);
    }//GEN-LAST:event_potoCancleBtnMouseMoved

    private void potoCancleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMouseClicked
        pathPhoto = "null";
        potoLabel.setIcon(new ImageIcon("src/mybank/resource/icon/user_100px.png"));
    }//GEN-LAST:event_potoCancleBtnMouseClicked

    private void potoCancleBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMouseExited
        btnStyle.borderMouseExit(potoCancleBtn);
    }//GEN-LAST:event_potoCancleBtnMouseExited

    private void potoCancleBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMousePressed
        btnStyle.backgroundMousePressed(potoCancleBtn);
    }//GEN-LAST:event_potoCancleBtnMousePressed

    private void potoCancleBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMouseReleased
        btnStyle.backgroundMouseReleased(potoCancleBtn);
    }//GEN-LAST:event_potoCancleBtnMouseReleased

    private void simpanBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanBtnMouseMoved
        btnStyle.borderMouseMoved(simpanBtn);
    }//GEN-LAST:event_simpanBtnMouseMoved

    private void simpanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanBtnMouseClicked
        if (tanggalLahirDate.getDate() != null) {
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            tglLahir = simpleDateFormat.format(tanggalLahirDate.getDate());
        }
        pegawaiCtrl.addPegawai(this);
    }//GEN-LAST:event_simpanBtnMouseClicked

    private void simpanBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanBtnMouseExited
        btnStyle.borderMouseExit(simpanBtn);
    }//GEN-LAST:event_simpanBtnMouseExited

    private void simpanBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanBtnMousePressed
        btnStyle.backgroundMousePressed(simpanBtn);
    }//GEN-LAST:event_simpanBtnMousePressed

    private void simpanBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanBtnMouseReleased
        btnStyle.backgroundMouseReleased(simpanBtn);
    }//GEN-LAST:event_simpanBtnMouseReleased

    private void closeBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseMoved
        closeBtn.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_closeBtnMouseMoved

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        btnStyle.backgroundMouseExit(closeBtn);
    }//GEN-LAST:event_closeBtnMouseExited

    private void closeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMousePressed
        btnStyle.backgroundMousePressed(closeBtn);
    }//GEN-LAST:event_closeBtnMousePressed

    private void closeBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseReleased
        closeBtn.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_closeBtnMouseReleased

    private void tanggalLahirDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalLahirDatePropertyChange
        if (tanggalLahirDate.getDate() != null) {
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            tglLahir = simpleDateFormat.format(tanggalLahirDate.getDate());
        }
    }//GEN-LAST:event_tanggalLahirDatePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PegawaiNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PegawaiNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PegawaiNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PegawaiNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PegawaiNew dialog = new PegawaiNew(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JabatanComboBox;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jkLakiLakiRadioButton;
    private javax.swing.JRadioButton jkPremepuanRadioButton;
    private javax.swing.JTextField namaLengkapTextField;
    private javax.swing.JTextField noKtpTextField;
    private javax.swing.JTextField noTlpTextField;
    private javax.swing.JLabel potoBtn;
    private javax.swing.JLabel potoCancleBtn;
    private javax.swing.JLabel potoLabel;
    private javax.swing.JLabel simpanBtn;
    private javax.swing.JPanel slide1Panel;
    private javax.swing.JPanel slide2Panel;
    private com.toedter.calendar.JDateChooser tanggalLahirDate;
    private javax.swing.JTextField tempatLahirTextFiled;
    private javax.swing.JLabel validasiPesanLabel;
    // End of variables declaration//GEN-END:variables
}
