/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myBank.view.manager.pegawai;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import myBank.controller.pegawaiController;
import myBank.model.PegawaiEntity;
import myBank.style.buttonStyle;

/**
 *
 * @author Fauzi
 */
public class PegawaiPanel extends javax.swing.JPanel {
    pegawaiController pegawaiCtrl = new pegawaiController();
    buttonStyle btnStyle = new buttonStyle();
    DefaultTableModel tableModel = new DefaultTableModel();
    private String idPegawai="";
    
    /**
     * Creates new form pegawaiPanel
     */
    public PegawaiPanel() {
        initComponents();
        tableModel.addColumn("ID Pegawai");
        tableModel.addColumn("No KTP");
        tableModel.addColumn("Nama");
        tableModel.addColumn("Jenis Kelamin");     
        tableModel.addColumn("Jabatan");
        pegawaiTable.setModel(tableModel);
        loadPegawaiTable();
        //ayy
    }
public void loadPegawaiTable() {
        List<PegawaiEntity> listPegawai = pegawaiCtrl.loadDataPegawai();
        tableModel.getDataVector().removeAllElements();
        for (PegawaiEntity pegawai : listPegawai) {
            Object[] item = new Object[5];
            item[0] = pegawai.getIdPegawai();
            item[1] = pegawai.getNoKtp();
            item[2] = pegawai.getNama();
            item[3] = pegawai.getJenisKelamin();            
            item[4] = pegawai.getJabatan();            
            tableModel.addRow(item);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        refreshBtn = new javax.swing.JLabel();
        cariTextField = new javax.swing.JTextField();
        cariBtn = new javax.swing.JLabel();
        cariTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        baruBtn = new javax.swing.JLabel();
        editBtn = new javax.swing.JLabel();
        hapusBtn = new javax.swing.JLabel();
        firstBtn = new javax.swing.JLabel();
        prevBtn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nextBtn = new javax.swing.JLabel();
        lastBtn = new javax.swing.JLabel();
        DetailBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pegawaiTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(32, 103, 178));
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(750, 600));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 60));

        refreshBtn.setBackground(new java.awt.Color(35, 171, 226));
        refreshBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/refresh_30px.png"))); // NOI18N
        refreshBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshBtn.setOpaque(true);
        refreshBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        refreshBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                refreshBtnMouseMoved(evt);
            }
        });
        refreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                refreshBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                refreshBtnMouseReleased(evt);
            }
        });

        cariTextField.setBackground(new java.awt.Color(32, 103, 178));
        cariTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cariTextField.setForeground(new java.awt.Color(255, 255, 255));
        cariTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        cariTextField.setPreferredSize(new java.awt.Dimension(59, 40));

        cariBtn.setBackground(new java.awt.Color(35, 171, 226));
        cariBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cariBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/cari_30px.png"))); // NOI18N
        cariBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cariBtn.setOpaque(true);
        cariBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        cariBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cariBtnMouseMoved(evt);
            }
        });
        cariBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cariBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cariBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cariBtnMouseReleased(evt);
            }
        });

        cariTextField1.setBackground(new java.awt.Color(32, 103, 178));
        cariTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cariTextField1.setForeground(new java.awt.Color(255, 255, 255));
        cariTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        cariTextField1.setPreferredSize(new java.awt.Dimension(59, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cariBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cariTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 60));

        baruBtn.setBackground(new java.awt.Color(35, 171, 226));
        baruBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        baruBtn.setForeground(new java.awt.Color(255, 255, 255));
        baruBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/newData_30px.png"))); // NOI18N
        baruBtn.setText("BARU");
        baruBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        baruBtn.setOpaque(true);
        baruBtn.setPreferredSize(new java.awt.Dimension(83, 40));
        baruBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                baruBtnMouseMoved(evt);
            }
        });
        baruBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baruBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                baruBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                baruBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                baruBtnMouseReleased(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(35, 171, 226));
        editBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/updateData_30px.png"))); // NOI18N
        editBtn.setText("EDIT");
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn.setOpaque(true);
        editBtn.setPreferredSize(new java.awt.Dimension(83, 40));
        editBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                editBtnMouseMoved(evt);
            }
        });
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editBtnMouseReleased(evt);
            }
        });

        hapusBtn.setBackground(new java.awt.Color(35, 171, 226));
        hapusBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hapusBtn.setForeground(new java.awt.Color(255, 255, 255));
        hapusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/deleteData_30px.png"))); // NOI18N
        hapusBtn.setText("HAPUS");
        hapusBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapusBtn.setOpaque(true);
        hapusBtn.setPreferredSize(new java.awt.Dimension(83, 40));
        hapusBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hapusBtnMouseMoved(evt);
            }
        });
        hapusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hapusBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hapusBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hapusBtnMouseReleased(evt);
            }
        });

        firstBtn.setBackground(new java.awt.Color(35, 171, 226));
        firstBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/firstPage_30px.png"))); // NOI18N
        firstBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        firstBtn.setOpaque(true);
        firstBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        firstBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                firstBtnMouseMoved(evt);
            }
        });
        firstBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                firstBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                firstBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                firstBtnMouseReleased(evt);
            }
        });

        prevBtn.setBackground(new java.awt.Color(35, 171, 226));
        prevBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prevBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/prevPage_30px.png"))); // NOI18N
        prevBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prevBtn.setOpaque(true);
        prevBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        prevBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                prevBtnMouseMoved(evt);
            }
        });
        prevBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prevBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                prevBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                prevBtnMouseReleased(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("1 Dari 100");
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 40));

        nextBtn.setBackground(new java.awt.Color(35, 171, 226));
        nextBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/nextPage_30px.png"))); // NOI18N
        nextBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextBtn.setOpaque(true);
        nextBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        nextBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                nextBtnMouseMoved(evt);
            }
        });
        nextBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nextBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nextBtnMouseReleased(evt);
            }
        });

        lastBtn.setBackground(new java.awt.Color(35, 171, 226));
        lastBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/lastPage_30px.png"))); // NOI18N
        lastBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lastBtn.setOpaque(true);
        lastBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        lastBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lastBtnMouseMoved(evt);
            }
        });
        lastBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lastBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lastBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lastBtnMouseReleased(evt);
            }
        });

        DetailBtn.setBackground(new java.awt.Color(35, 171, 226));
        DetailBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DetailBtn.setForeground(new java.awt.Color(255, 255, 255));
        DetailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/detailData_30px.png"))); // NOI18N
        DetailBtn.setText("DETAIL");
        DetailBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DetailBtn.setOpaque(true);
        DetailBtn.setPreferredSize(new java.awt.Dimension(83, 40));
        DetailBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DetailBtnMouseMoved(evt);
            }
        });
        DetailBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DetailBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DetailBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DetailBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DetailBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(baruBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hapusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DetailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(firstBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(baruBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DetailBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        pegawaiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pegawaiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pegawaiTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pegawaiTable);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void baruBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baruBtnMouseMoved
        btnStyle.borderMouseMoved(baruBtn);
    }//GEN-LAST:event_baruBtnMouseMoved

    private void baruBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baruBtnMouseClicked
        new PegawaiNew(null, true, this).show();
    }//GEN-LAST:event_baruBtnMouseClicked

    private void baruBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baruBtnMouseExited
        btnStyle.borderMouseExit(baruBtn);
    }//GEN-LAST:event_baruBtnMouseExited

    private void baruBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baruBtnMousePressed
        btnStyle.backgroundMousePressed(baruBtn);
    }//GEN-LAST:event_baruBtnMousePressed

    private void baruBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baruBtnMouseReleased
        btnStyle.backgroundMouseReleased(baruBtn);
    }//GEN-LAST:event_baruBtnMouseReleased

    private void editBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseMoved
        btnStyle.borderMouseMoved(editBtn);
    }//GEN-LAST:event_editBtnMouseMoved

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        if(idPegawai.equals("")){
            JOptionPane.showMessageDialog(null, "Tentukan data pegawai yang akan diedit");
        }else{
            new pegawaiEdit(null, true,this ).show();
        }
    }//GEN-LAST:event_editBtnMouseClicked

    private void editBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseExited
        btnStyle.borderMouseExit(editBtn);
    }//GEN-LAST:event_editBtnMouseExited

    private void editBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMousePressed
        btnStyle.backgroundMousePressed(editBtn);
    }//GEN-LAST:event_editBtnMousePressed

    private void editBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseReleased
        btnStyle.backgroundMouseReleased(editBtn);
    }//GEN-LAST:event_editBtnMouseReleased

    private void hapusBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusBtnMouseMoved
        btnStyle.borderMouseMoved(hapusBtn);
    }//GEN-LAST:event_hapusBtnMouseMoved

    private void hapusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusBtnMouseClicked
        
    }//GEN-LAST:event_hapusBtnMouseClicked

    private void hapusBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusBtnMouseExited
        btnStyle.borderMouseExit(hapusBtn);
    }//GEN-LAST:event_hapusBtnMouseExited

    private void hapusBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusBtnMousePressed
        btnStyle.backgroundMousePressed(hapusBtn);
    }//GEN-LAST:event_hapusBtnMousePressed

    private void hapusBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusBtnMouseReleased
        btnStyle.backgroundMouseReleased(hapusBtn);
    }//GEN-LAST:event_hapusBtnMouseReleased

    private void firstBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstBtnMouseMoved
        btnStyle.borderMouseMoved(firstBtn);
    }//GEN-LAST:event_firstBtnMouseMoved

    private void firstBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstBtnMouseExited
        btnStyle.borderMouseExit(firstBtn);
    }//GEN-LAST:event_firstBtnMouseExited

    private void firstBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstBtnMousePressed
        btnStyle.backgroundMousePressed(firstBtn);
    }//GEN-LAST:event_firstBtnMousePressed

    private void firstBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstBtnMouseReleased
        btnStyle.backgroundMouseReleased(firstBtn);
    }//GEN-LAST:event_firstBtnMouseReleased

    private void prevBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevBtnMouseMoved
        btnStyle.borderMouseMoved(prevBtn);
    }//GEN-LAST:event_prevBtnMouseMoved

    private void prevBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevBtnMouseExited
        btnStyle.borderMouseExit(prevBtn);
    }//GEN-LAST:event_prevBtnMouseExited

    private void prevBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevBtnMousePressed
        btnStyle.backgroundMousePressed(prevBtn);
    }//GEN-LAST:event_prevBtnMousePressed

    private void prevBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevBtnMouseReleased
        btnStyle.backgroundMouseReleased(prevBtn);
    }//GEN-LAST:event_prevBtnMouseReleased

    private void nextBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtnMouseMoved
        btnStyle.borderMouseMoved(nextBtn);
    }//GEN-LAST:event_nextBtnMouseMoved

    private void nextBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtnMouseExited
        btnStyle.borderMouseExit(nextBtn);
    }//GEN-LAST:event_nextBtnMouseExited

    private void nextBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtnMousePressed
        btnStyle.backgroundMousePressed(nextBtn);
    }//GEN-LAST:event_nextBtnMousePressed

    private void nextBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtnMouseReleased
        btnStyle.backgroundMouseReleased(nextBtn);
    }//GEN-LAST:event_nextBtnMouseReleased

    private void lastBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastBtnMouseMoved
        btnStyle.borderMouseMoved(lastBtn);
    }//GEN-LAST:event_lastBtnMouseMoved

    private void lastBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastBtnMouseExited
        btnStyle.borderMouseExit(lastBtn);
    }//GEN-LAST:event_lastBtnMouseExited

    private void lastBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastBtnMousePressed
        btnStyle.backgroundMousePressed(lastBtn);
    }//GEN-LAST:event_lastBtnMousePressed

    private void lastBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastBtnMouseReleased
        btnStyle.backgroundMouseReleased(lastBtn);
    }//GEN-LAST:event_lastBtnMouseReleased

    private void refreshBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseMoved
        btnStyle.borderMouseMoved(refreshBtn);
    }//GEN-LAST:event_refreshBtnMouseMoved

    private void refreshBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseClicked
   
    }//GEN-LAST:event_refreshBtnMouseClicked

    private void refreshBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseExited
        btnStyle.borderMouseExit(refreshBtn);
    }//GEN-LAST:event_refreshBtnMouseExited

    private void refreshBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMousePressed
        btnStyle.backgroundMousePressed(refreshBtn);
    }//GEN-LAST:event_refreshBtnMousePressed

    private void refreshBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseReleased
        btnStyle.backgroundMouseReleased(refreshBtn);
    }//GEN-LAST:event_refreshBtnMouseReleased

    private void cariBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariBtnMouseMoved
        btnStyle.borderMouseMoved(cariBtn);
    }//GEN-LAST:event_cariBtnMouseMoved

    private void cariBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariBtnMouseClicked

    }//GEN-LAST:event_cariBtnMouseClicked

    private void cariBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariBtnMouseExited
        btnStyle.borderMouseExit(cariBtn);
    }//GEN-LAST:event_cariBtnMouseExited

    private void cariBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariBtnMousePressed
        btnStyle.backgroundMousePressed(cariBtn);
    }//GEN-LAST:event_cariBtnMousePressed

    private void cariBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariBtnMouseReleased
        btnStyle.backgroundMouseReleased(cariBtn);
    }//GEN-LAST:event_cariBtnMouseReleased

    private void DetailBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailBtnMouseMoved
        btnStyle.borderMouseMoved(DetailBtn);
    }//GEN-LAST:event_DetailBtnMouseMoved

    private void DetailBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailBtnMouseClicked
        
    }//GEN-LAST:event_DetailBtnMouseClicked

    private void DetailBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailBtnMouseExited
        btnStyle.borderMouseExit(DetailBtn);
    }//GEN-LAST:event_DetailBtnMouseExited

    private void DetailBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailBtnMousePressed
        btnStyle.backgroundMousePressed(DetailBtn);
    }//GEN-LAST:event_DetailBtnMousePressed

    private void DetailBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailBtnMouseReleased
        btnStyle.backgroundMouseReleased(DetailBtn);
    }//GEN-LAST:event_DetailBtnMouseReleased

    private void pegawaiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pegawaiTableMouseClicked
        int row = pegawaiTable.getSelectedRow();
        idPegawai = pegawaiTable.getValueAt(row, 0).toString();
    }//GEN-LAST:event_pegawaiTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DetailBtn;
    private javax.swing.JLabel baruBtn;
    private javax.swing.JLabel cariBtn;
    private javax.swing.JTextField cariTextField;
    private javax.swing.JTextField cariTextField1;
    private javax.swing.JLabel editBtn;
    private javax.swing.JLabel firstBtn;
    private javax.swing.JLabel hapusBtn;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastBtn;
    private javax.swing.JLabel nextBtn;
    private javax.swing.JTable pegawaiTable;
    private javax.swing.JLabel prevBtn;
    private javax.swing.JLabel refreshBtn;
    // End of variables declaration//GEN-END:variables

    public String getIdPegawai() {
        return idPegawai;
    }
}
