/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myBank.view.customerService;

import java.awt.Color;
import javax.swing.JPanel;
import myBank.view.customerService.nasabah.nasabahPanel;
import myBank.style.buttonStyle;

/**
 *
 * @author Fauzi
 */
public class customerServiceFrame extends javax.swing.JFrame {
    buttonStyle style = new buttonStyle();
    nasabahPanel nasabah = new nasabahPanel();

    /**
     * Creates new form customerServiceFrame
     */
    public customerServiceFrame() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);        
    }

    private void showPanel(JPanel panel, String titleMenu) {
        mainContentPanel.removeAll();
        mainContentPanel.repaint();
        mainContentPanel.revalidate();
        mainContentPanel.add(panel);
        titleLabel.setText(titleMenu);
        mainContentPanel.repaint();
        mainContentPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barPanel = new javax.swing.JPanel();
        closeBtn = new javax.swing.JLabel();
        maximizeBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namaNasabahLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        nasabahMenu = new javax.swing.JPanel();
        nasabahLabel = new javax.swing.JLabel();
        tabunganMenu = new javax.swing.JPanel();
        tabunganLabel = new javax.swing.JLabel();
        logoutMenu = new javax.swing.JPanel();
        logoutLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        mainContentPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barPanel.setBackground(new java.awt.Color(32, 103, 178));
        barPanel.setPreferredSize(new java.awt.Dimension(752, 30));

        closeBtn.setBackground(new java.awt.Color(32, 103, 178));
        closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/close_screen_20px.png"))); // NOI18N
        closeBtn.setOpaque(true);
        closeBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        closeBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeBtnMouseMoved(evt);
            }
        });
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeBtnMouseReleased(evt);
            }
        });

        maximizeBtn.setBackground(new java.awt.Color(32, 103, 178));
        maximizeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maximizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/normal_screen_20px.png"))); // NOI18N
        maximizeBtn.setOpaque(true);
        maximizeBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        maximizeBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                maximizeBtnMouseMoved(evt);
            }
        });
        maximizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maximizeBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maximizeBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                maximizeBtnMouseReleased(evt);
            }
        });

        minimizeBtn.setBackground(new java.awt.Color(32, 103, 178));
        minimizeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/minimize_Screen_20px.png"))); // NOI18N
        minimizeBtn.setOpaque(true);
        minimizeBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        minimizeBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseMoved(evt);
            }
        });
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizeBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout barPanelLayout = new javax.swing.GroupLayout(barPanel);
        barPanel.setLayout(barPanelLayout);
        barPanelLayout.setHorizontalGroup(
            barPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barPanelLayout.createSequentialGroup()
                .addGap(0, 650, Short.MAX_VALUE)
                .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maximizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barPanelLayout.setVerticalGroup(
            barPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(maximizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(minimizeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(barPanel, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        sidebarPanel.setPreferredSize(new java.awt.Dimension(200, 302));
        sidebarPanel.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(32, 103, 178));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 150));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/user_100px.png"))); // NOI18N

        namaNasabahLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namaNasabahLabel.setForeground(new java.awt.Color(255, 255, 255));
        namaNasabahLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaNasabahLabel.setText("nama CS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(namaNasabahLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaNasabahLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        sidebarPanel.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(32, 103, 178));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nasabahMenu.setBackground(new java.awt.Color(32, 103, 178));
        nasabahMenu.setPreferredSize(new java.awt.Dimension(200, 40));

        nasabahLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nasabahLabel.setForeground(new java.awt.Color(255, 255, 255));
        nasabahLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/menuNasabah_30px.png"))); // NOI18N
        nasabahLabel.setText("NASABAH");
        nasabahLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nasabahLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                nasabahLabelMouseMoved(evt);
            }
        });
        nasabahLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nasabahLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nasabahLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nasabahLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nasabahLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout nasabahMenuLayout = new javax.swing.GroupLayout(nasabahMenu);
        nasabahMenu.setLayout(nasabahMenuLayout);
        nasabahMenuLayout.setHorizontalGroup(
            nasabahMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nasabahMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nasabahLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );
        nasabahMenuLayout.setVerticalGroup(
            nasabahMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nasabahLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel6.add(nasabahMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        tabunganMenu.setBackground(new java.awt.Color(32, 103, 178));
        tabunganMenu.setPreferredSize(new java.awt.Dimension(200, 40));

        tabunganLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabunganLabel.setForeground(new java.awt.Color(255, 255, 255));
        tabunganLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/tabunganMenu_30px.png"))); // NOI18N
        tabunganLabel.setText("TABUNGAN");
        tabunganLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabunganLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tabunganLabelMouseMoved(evt);
            }
        });
        tabunganLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabunganLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabunganLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabunganLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout tabunganMenuLayout = new javax.swing.GroupLayout(tabunganMenu);
        tabunganMenu.setLayout(tabunganMenuLayout);
        tabunganMenuLayout.setHorizontalGroup(
            tabunganMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabunganMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabunganLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );
        tabunganMenuLayout.setVerticalGroup(
            tabunganMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabunganLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel6.add(tabunganMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, -1));

        logoutMenu.setBackground(new java.awt.Color(32, 103, 178));
        logoutMenu.setPreferredSize(new java.awt.Dimension(200, 40));

        logoutLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/logOut_30px.png"))); // NOI18N
        logoutLabel.setText("LOG OUT");
        logoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logoutLabelMouseMoved(evt);
            }
        });
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout logoutMenuLayout = new javax.swing.GroupLayout(logoutMenu);
        logoutMenu.setLayout(logoutMenuLayout);
        logoutMenuLayout.setHorizontalGroup(
            logoutMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );
        logoutMenuLayout.setVerticalGroup(
            logoutMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel6.add(logoutMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, -1));

        sidebarPanel.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel4.add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        contentPanel.setBackground(new java.awt.Color(32, 103, 178));
        contentPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(32, 103, 178));
        headerPanel.setPreferredSize(new java.awt.Dimension(547, 150));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Customer Service");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 161, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(0, 111, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contentPanel.add(headerPanel, java.awt.BorderLayout.PAGE_START);

        mainContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainContentPanel.setLayout(new java.awt.BorderLayout());
        contentPanel.add(mainContentPanel, java.awt.BorderLayout.CENTER);

        jPanel4.add(contentPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(32, 103, 178));
        jPanel2.setPreferredSize(new java.awt.Dimension(5, 302));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(32, 103, 178));
        jPanel3.setPreferredSize(new java.awt.Dimension(5, 5));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(32, 103, 178));
        jPanel1.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseExited
        style.backgroundMouseExit(minimizeBtn);
    }//GEN-LAST:event_minimizeBtnMouseExited

    private void minimizeBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseMoved
        style.backgroundMouseMoved(minimizeBtn);
    }//GEN-LAST:event_minimizeBtnMouseMoved

    private void minimizeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMousePressed
        style.backgroundMousePressed(minimizeBtn);
    }//GEN-LAST:event_minimizeBtnMousePressed

    private void minimizeBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseReleased
        style.backgroundMouseReleased(minimizeBtn);
    }//GEN-LAST:event_minimizeBtnMouseReleased

    private void maximizeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeBtnMouseExited
        style.backgroundMouseExit(maximizeBtn);
    }//GEN-LAST:event_maximizeBtnMouseExited

    private void maximizeBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeBtnMouseMoved
        style.backgroundMouseMoved(maximizeBtn);
    }//GEN-LAST:event_maximizeBtnMouseMoved

    private void maximizeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeBtnMousePressed
        style.backgroundMousePressed(maximizeBtn);
    }//GEN-LAST:event_maximizeBtnMousePressed

    private void maximizeBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeBtnMouseReleased
        style.backgroundMouseReleased(maximizeBtn);
    }//GEN-LAST:event_maximizeBtnMouseReleased

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        style.backgroundMouseExit(closeBtn);
    }//GEN-LAST:event_closeBtnMouseExited

    private void closeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMousePressed
        style.backgroundMousePressed(closeBtn);
    }//GEN-LAST:event_closeBtnMousePressed

    private void closeBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseMoved
        closeBtn.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_closeBtnMouseMoved

    private void closeBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseReleased
        closeBtn.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_closeBtnMouseReleased

    private void nasabahLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nasabahLabelMouseExited
        style.backgroundMouseExit(nasabahMenu);
    }//GEN-LAST:event_nasabahLabelMouseExited

    private void nasabahLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nasabahLabelMouseMoved
        style.backgroundMouseMoved(nasabahMenu);
    }//GEN-LAST:event_nasabahLabelMouseMoved

    private void nasabahLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nasabahLabelMousePressed
        style.backgroundMousePressed(nasabahMenu);
    }//GEN-LAST:event_nasabahLabelMousePressed

    private void nasabahLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nasabahLabelMouseReleased
        style.backgroundMouseReleased(nasabahMenu);
    }//GEN-LAST:event_nasabahLabelMouseReleased

    private void tabunganLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabunganLabelMouseExited
        style.backgroundMouseExit(tabunganMenu);
    }//GEN-LAST:event_tabunganLabelMouseExited

    private void tabunganLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabunganLabelMouseMoved
        style.backgroundMouseMoved(tabunganMenu);
    }//GEN-LAST:event_tabunganLabelMouseMoved

    private void tabunganLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabunganLabelMousePressed
        style.backgroundMousePressed(tabunganMenu);
    }//GEN-LAST:event_tabunganLabelMousePressed

    private void tabunganLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabunganLabelMouseReleased
        style.backgroundMouseReleased(tabunganMenu);
    }//GEN-LAST:event_tabunganLabelMouseReleased

    private void logoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        style.backgroundMouseExit(logoutMenu);
    }//GEN-LAST:event_logoutLabelMouseExited

    private void logoutLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseMoved
        style.backgroundMouseMoved(logoutMenu);
    }//GEN-LAST:event_logoutLabelMouseMoved

    private void logoutLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMousePressed
        style.backgroundMousePressed(logoutMenu);
    }//GEN-LAST:event_logoutLabelMousePressed

    private void logoutLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseReleased
        style.backgroundMouseReleased(logoutMenu);
    }//GEN-LAST:event_logoutLabelMouseReleased

    private void nasabahLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nasabahLabelMouseClicked
        showPanel(nasabah, "DATA NASABAH");
    }//GEN-LAST:event_nasabahLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerServiceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barPanel;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel logoutMenu;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JLabel maximizeBtn;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel namaNasabahLabel;
    private javax.swing.JLabel nasabahLabel;
    private javax.swing.JPanel nasabahMenu;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel tabunganLabel;
    private javax.swing.JPanel tabunganMenu;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
