/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myBank.view.customerService.nasabah;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import myBank.controller.nasabahController;
import myBank.style.buttonStyle;
import myBank.style.photoStyle;

/**
 *
 * @author Fauzi
 */
public class NasabahEdit extends javax.swing.JDialog {

    nasabahController nasabahCtrl = new nasabahController();
    ButtonGroup radioGroup = new ButtonGroup();
    buttonStyle btnStyle = new buttonStyle();
    photoStyle photoStyle = new photoStyle();
    private String pathPhoto = "null";
    private String namaPhoto = "";
    private String tanggalLahir;
    private String idNasabah = "";
    private String pathRestorePhoto = "null";
    private String noRestoreKTP = "";

    /**
     * Creates new form NasabahEdit
     */
    public NasabahEdit(java.awt.Frame parent, boolean modal, String idNasabah, String noKtp, String nama, String jk, String tempatLahir, Date tglLahir, String alamat, String noTlp, String photo) {
        super(parent, modal);
        initComponents();
        radioGroup.add(jKLakiRB);
        radioGroup.add(jkPerempuanRB);
        this.idNasabah = idNasabah;
        noRestoreKTP = noKtp;
        noKTPTextField.setText(noKtp);
        namaTextField.setText(nama);
        if (jk.equals("Laki - laki")) {
            jKLakiRB.setSelected(true);
        } else {
            jkPerempuanRB.setSelected(true);
        }
        tempatLahirTextField.setText(tempatLahir);
        tanggalLahirDate.setDate(tglLahir);
        alamatTextArea.setText(alamat);
        noTlpTextField.setText(noTlp);
        namaPhoto = photo;
        if (photo.equals("null")) {
            potoLabel.setIcon(new ImageIcon("src/mybank/resource/icon/user_100px.png"));
            pathRestorePhoto ="null";
            pathPhoto ="null";
        } else {
            pathPhoto = "src/mybank/resource/photo/" + photo;
            pathRestorePhoto = pathPhoto;
            BufferedImage loadImg = photoStyle.loadImage(pathPhoto);
            ImageIcon imageIcon = new ImageIcon(photoStyle.resize(loadImg, potoLabel.getWidth() - 1, potoLabel.getHeight() - 1));
            potoLabel.setIcon(imageIcon);
        }
        tanggalLahirDate.setDateFormatString("yyyy-MM-dd");
        validasiPesanLabel.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    public NasabahEdit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        radioGroup.add(jKLakiRB);
        radioGroup.add(jkPerempuanRB);
        tanggalLahirDate.setDateFormatString("yyyy-MM-dd");
        validasiPesanLabel.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    public void setValidasi(String pesan, boolean stts) {
        validasiPesanLabel.setText(pesan);
        validasiPesanLabel.setVisible(stts);
    }

    public String getNamaPhoto() {
        return namaPhoto;
    }

    public String getIdNasabah() {
        return idNasabah;
    }

    public String getPathRsetorePhoto() {
        return pathRestorePhoto;
    }

    public String getRestoreNoKTP() {
        return noRestoreKTP;
    }

    public JTextField getNoKTP() {
        return noKTPTextField;
    }

    public JTextField getNama() {
        return namaTextField;
    }

    public JRadioButton getJkLaki() {
        return jKLakiRB;
    }

    public JRadioButton getJkPerempuan() {
        return jkPerempuanRB;
    }

    public JTextField getTempatLahir() {
        return tempatLahirTextField;
    }

    public String getTanggalLahir() {
        return tanggalLahir;
    }

    public JTextField getNoTlp() {
        return noTlpTextField;
    }

    public JTextArea getAlamat() {
        return alamatTextArea;
    }

    public String getPathPhoto() {
        return pathPhoto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        closeBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        slinde1Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        noKTPTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        jKLakiRB = new javax.swing.JRadioButton();
        jkPerempuanRB = new javax.swing.JRadioButton();
        tempatLahirTextField = new javax.swing.JTextField();
        noTlpTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        potoLabel = new javax.swing.JLabel();
        potoBtn = new javax.swing.JLabel();
        editBtn = new javax.swing.JLabel();
        validasiPesanLabel = new javax.swing.JLabel();
        tanggalLahirDate = new com.toedter.calendar.JDateChooser();
        potoCancleBtn = new javax.swing.JLabel();
        potoundoBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(750, 600));
        setSize(new java.awt.Dimension(750, 600));

        jPanel1.setBackground(new java.awt.Color(32, 103, 178));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(719, 30));

        closeBtn.setBackground(new java.awt.Color(32, 103, 178));
        closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/close_screen_20px.png"))); // NOI18N
        closeBtn.setOpaque(true);
        closeBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeBtnMouseMoved(evt);
            }
        });
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeBtnMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EDIT DATA NASABAH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel4.setLayout(new java.awt.CardLayout());

        slinde1Panel.setBackground(new java.awt.Color(32, 103, 178));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No KTP");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Lengkap");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tempat Lahir");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal Lahir");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alamat Lengkap");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No Telepon");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jenis Kelamin");

        noKTPTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noKTPTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        namaTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        jKLakiRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jKLakiRB.setForeground(new java.awt.Color(255, 255, 255));
        jKLakiRB.setSelected(true);
        jKLakiRB.setText("Laki - laki");
        jKLakiRB.setOpaque(false);

        jkPerempuanRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jkPerempuanRB.setForeground(new java.awt.Color(255, 255, 255));
        jkPerempuanRB.setText("Perempuan");
        jkPerempuanRB.setOpaque(false);

        tempatLahirTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tempatLahirTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        noTlpTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noTlpTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        alamatTextArea.setColumns(20);
        alamatTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alamatTextArea.setLineWrap(true);
        alamatTextArea.setRows(5);
        alamatTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        alamatTextArea.setOpaque(false);
        jScrollPane1.setViewportView(alamatTextArea);

        potoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        potoLabel.setForeground(new java.awt.Color(255, 255, 255));
        potoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/user_100px.png"))); // NOI18N
        potoLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        potoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        potoLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        potoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        potoBtn.setBackground(new java.awt.Color(35, 171, 226));
        potoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/cari_30px.png"))); // NOI18N
        potoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        potoBtn.setOpaque(true);
        potoBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                potoBtnMouseMoved(evt);
            }
        });
        potoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potoBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                potoBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                potoBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                potoBtnMouseReleased(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(35, 171, 226));
        editBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/updateData_30px.png"))); // NOI18N
        editBtn.setText("EDIT");
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn.setOpaque(true);
        editBtn.setPreferredSize(new java.awt.Dimension(34, 40));
        editBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                editBtnMouseMoved(evt);
            }
        });
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editBtnMouseReleased(evt);
            }
        });

        validasiPesanLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        validasiPesanLabel.setForeground(new java.awt.Color(255, 255, 255));
        validasiPesanLabel.setText("*Pesan Validasi");
        validasiPesanLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Catatan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        tanggalLahirDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalLahirDatePropertyChange(evt);
            }
        });

        potoCancleBtn.setBackground(new java.awt.Color(35, 171, 226));
        potoCancleBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potoCancleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/cancle_30px.png"))); // NOI18N
        potoCancleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        potoCancleBtn.setOpaque(true);
        potoCancleBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                potoCancleBtnMouseMoved(evt);
            }
        });
        potoCancleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potoCancleBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                potoCancleBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                potoCancleBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                potoCancleBtnMouseReleased(evt);
            }
        });

        potoundoBtn.setBackground(new java.awt.Color(35, 171, 226));
        potoundoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potoundoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/undo_30px.png"))); // NOI18N
        potoundoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        potoundoBtn.setOpaque(true);
        potoundoBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                potoundoBtnMouseMoved(evt);
            }
        });
        potoundoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potoundoBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                potoundoBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                potoundoBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                potoundoBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout slinde1PanelLayout = new javax.swing.GroupLayout(slinde1Panel);
        slinde1Panel.setLayout(slinde1PanelLayout);
        slinde1PanelLayout.setHorizontalGroup(
            slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slinde1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tanggalLahirDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, slinde1PanelLayout.createSequentialGroup()
                        .addComponent(jKLakiRB)
                        .addGap(27, 27, 27)
                        .addComponent(jkPerempuanRB))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noKTPTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(tempatLahirTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(noTlpTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(slinde1PanelLayout.createSequentialGroup()
                        .addComponent(validasiPesanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slinde1PanelLayout.createSequentialGroup()
                        .addGap(0, 137, Short.MAX_VALUE)
                        .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slinde1PanelLayout.createSequentialGroup()
                                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slinde1PanelLayout.createSequentialGroup()
                                .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(potoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(slinde1PanelLayout.createSequentialGroup()
                                        .addComponent(potoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(potoundoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(potoCancleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(91, 91, 91))))))
        );
        slinde1PanelLayout.setVerticalGroup(
            slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slinde1PanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(slinde1PanelLayout.createSequentialGroup()
                        .addComponent(noKTPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jKLakiRB)
                            .addComponent(jkPerempuanRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tempatLahirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(slinde1PanelLayout.createSequentialGroup()
                        .addComponent(potoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(potoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(potoCancleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(potoundoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalLahirDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTlpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validasiPesanLabel))
                .addGap(11, 11, 11)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jPanel4.add(slinde1Panel, "card2");

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseMoved
        closeBtn.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_closeBtnMouseMoved

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        btnStyle.backgroundMouseExit(closeBtn);
    }//GEN-LAST:event_closeBtnMouseExited

    private void closeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMousePressed
        btnStyle.backgroundMousePressed(closeBtn);
    }//GEN-LAST:event_closeBtnMousePressed

    private void closeBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseReleased
        closeBtn.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_closeBtnMouseReleased

    private void potoBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMouseMoved
        btnStyle.borderMouseMoved(potoBtn);
    }//GEN-LAST:event_potoBtnMouseMoved

    private void potoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMouseClicked
        JFileChooser jfc = new JFileChooser();
        FileFilter pngFilter = new FileNameExtensionFilter("Gambar GIF", "png");
        jfc.setAcceptAllFileFilterUsed(false);
        jfc.addChoosableFileFilter(pngFilter);
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            pathPhoto = jfc.getSelectedFile().toString();
            if (!"".equals(pathPhoto)) {
                pathPhoto = pathPhoto.replace("\\", "/");
                BufferedImage loadImg = photoStyle.loadImage(pathPhoto);
                ImageIcon imageIcon = new ImageIcon(photoStyle.resize(loadImg, potoLabel.getWidth() - 1, potoLabel.getHeight() - 1));
                potoLabel.setIcon(imageIcon);
            }
        }
    }//GEN-LAST:event_potoBtnMouseClicked

    private void potoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMouseExited
        btnStyle.borderMouseExit(potoBtn);
    }//GEN-LAST:event_potoBtnMouseExited

    private void potoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMousePressed
        btnStyle.backgroundMousePressed(potoBtn);
    }//GEN-LAST:event_potoBtnMousePressed

    private void potoBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMouseReleased
        btnStyle.backgroundMouseReleased(potoBtn);
    }//GEN-LAST:event_potoBtnMouseReleased

    private void editBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseMoved
        btnStyle.borderMouseMoved(editBtn);
    }//GEN-LAST:event_editBtnMouseMoved

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        if (tanggalLahirDate.getDate() != null) {
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            tanggalLahir = simpleDateFormat.format(tanggalLahirDate.getDate());
        }
        nasabahCtrl.editNasabah(this);
    }//GEN-LAST:event_editBtnMouseClicked

    private void editBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseExited
        btnStyle.borderMouseExit(editBtn);
    }//GEN-LAST:event_editBtnMouseExited

    private void editBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMousePressed
        btnStyle.backgroundMousePressed(editBtn);
    }//GEN-LAST:event_editBtnMousePressed

    private void editBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseReleased
        btnStyle.backgroundMouseReleased(editBtn);
    }//GEN-LAST:event_editBtnMouseReleased

    private void tanggalLahirDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalLahirDatePropertyChange
        if (tanggalLahirDate.getDate() != null) {
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            tanggalLahir = simpleDateFormat.format(tanggalLahirDate.getDate());
        }
    }//GEN-LAST:event_tanggalLahirDatePropertyChange

    private void potoCancleBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMouseMoved
        btnStyle.borderMouseMoved(potoCancleBtn);
    }//GEN-LAST:event_potoCancleBtnMouseMoved

    private void potoCancleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMouseClicked
        pathPhoto = "null";
        potoLabel.setIcon(new ImageIcon("src/mybank/resource/icon/user_100px.png"));
    }//GEN-LAST:event_potoCancleBtnMouseClicked

    private void potoCancleBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMouseExited
        btnStyle.borderMouseExit(potoCancleBtn);
    }//GEN-LAST:event_potoCancleBtnMouseExited

    private void potoCancleBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMousePressed
        btnStyle.backgroundMousePressed(potoCancleBtn);
    }//GEN-LAST:event_potoCancleBtnMousePressed

    private void potoCancleBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMouseReleased
        btnStyle.backgroundMouseReleased(potoCancleBtn);
    }//GEN-LAST:event_potoCancleBtnMouseReleased

    private void potoundoBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoundoBtnMouseMoved
        btnStyle.borderMouseMoved(potoundoBtn);
    }//GEN-LAST:event_potoundoBtnMouseMoved

    private void potoundoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoundoBtnMouseClicked
        if (!"null".equals(pathRestorePhoto)) {
            pathPhoto = pathRestorePhoto;
            BufferedImage loadImg = photoStyle.loadImage(pathPhoto);
            ImageIcon imageIcon = new ImageIcon(photoStyle.resize(loadImg, potoLabel.getWidth() - 1, potoLabel.getHeight() - 1));
            potoLabel.setIcon(imageIcon);
        }
    }//GEN-LAST:event_potoundoBtnMouseClicked

    private void potoundoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoundoBtnMouseExited
        btnStyle.borderMouseExit(potoundoBtn);
    }//GEN-LAST:event_potoundoBtnMouseExited

    private void potoundoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoundoBtnMousePressed
        btnStyle.backgroundMousePressed(potoundoBtn);
    }//GEN-LAST:event_potoundoBtnMousePressed

    private void potoundoBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoundoBtnMouseReleased
        btnStyle.backgroundMouseReleased(potoundoBtn);
    }//GEN-LAST:event_potoundoBtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NasabahEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NasabahEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NasabahEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NasabahEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NasabahEdit dialog = new NasabahEdit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel editBtn;
    private javax.swing.JRadioButton jKLakiRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jkPerempuanRB;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField noKTPTextField;
    private javax.swing.JTextField noTlpTextField;
    private javax.swing.JLabel potoBtn;
    private javax.swing.JLabel potoCancleBtn;
    private javax.swing.JLabel potoLabel;
    private javax.swing.JLabel potoundoBtn;
    private javax.swing.JPanel slinde1Panel;
    private com.toedter.calendar.JDateChooser tanggalLahirDate;
    private javax.swing.JTextField tempatLahirTextField;
    private javax.swing.JLabel validasiPesanLabel;
    // End of variables declaration//GEN-END:variables
}
