/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myBank.view.customerService.nasabah;

import java.awt.Color;
import static java.awt.Frame.ICONIFIED;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileFilter;
import javax.swing.JFileChooser;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import myBank.controller.nasabahController;
import myBank.style.buttonStyle;
import myBank.style.photoStyle;

/**
 *
 * @author Fauzi
 */
public class nasabahNew extends javax.swing.JDialog {

    nasabahController nasabahCtrl = new nasabahController();
    ButtonGroup radioGroup = new ButtonGroup();
    buttonStyle btnStyle = new buttonStyle();
    photoStyle photoStyle = new photoStyle();
    String pathPhoto = "null";
    String tanggalLahir;

    /**
     * Creates new form nasabahNew
     *
     * @param parent
     * @param modal
     */
    public nasabahNew(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tanggalLahirDate.setDateFormatString("yyyy-MM-dd");
        radioGroup.add(jKLakiRB);
        radioGroup.add(jkPerempuanRB);
        this.setLocationRelativeTo(null);
        validasiPesanLabel.setVisible(false);
        slinde1Panel.setVisible(true);
        slide2Panel.setVisible(false);
    }

    public void setDataNasabah(String noRek, String noKTP, String nama, String jenisKelamin, String ttl, String alamat, double saldo, String idNasabah, String password) {
        noRekLabel.setText(": " + noRek);
        noKTPLabel.setText(": " + noKTP);
        namaLabel.setText(": " + nama);
        jenisKelaminLabel.setText(": " + jenisKelamin);
        TTLLabel.setText(": " + ttl);
        alamatLabel.setText(": " + alamat);
        saldoLabel.setText(": Rp " + saldo);
        idNasabahLabel.setText(": " + idNasabah);
        passwordLabel.setText(": " + password);
    }

    public void setSlide2() {
        slide2Panel.setVisible(true);
        slinde1Panel.setVisible(false);
    }

    public void setValidasi(String pesan, boolean stts) {
        validasiPesanLabel.setText(pesan);
        validasiPesanLabel.setVisible(stts);
    }

    public JTextField getNoKTP() {
        return noKTPTextField;
    }

    public JTextField getNama() {
        return namaTextField;
    }

    public JRadioButton getJkLaki() {
        return jKLakiRB;
    }

    public JRadioButton getJkPerempuan() {
        return jkPerempuanRB;
    }

    public JTextField getTempatLahir() {
        return tempatLahirTextField;
    }

    public String getTanggalLahir() {
        return tanggalLahir;
    }

    public JTextField getNoTlp() {
        return noTlpTextField;
    }

    public JTextArea getAlamat() {
        return alamatTextArea;
    }

    public JTextField getSaldo() {
        return saldoTextField;
    }

    public String getPathPhoto() {
        return pathPhoto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        closeBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        slinde1Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        noKTPTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        jKLakiRB = new javax.swing.JRadioButton();
        jkPerempuanRB = new javax.swing.JRadioButton();
        tempatLahirTextField = new javax.swing.JTextField();
        noTlpTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        saldoTextField = new javax.swing.JTextField();
        potoLabel = new javax.swing.JLabel();
        potoBtn = new javax.swing.JLabel();
        simpanBtn = new javax.swing.JLabel();
        validasiPesanLabel = new javax.swing.JLabel();
        tanggalLahirDate = new com.toedter.calendar.JDateChooser();
        potoCancleBtn = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        slide2Panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        printnBtn = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        noRekLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        noKTPLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        jenisKelaminLabel = new javax.swing.JLabel();
        TTLLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        saldoLabel = new javax.swing.JLabel();
        idNasabahLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(750, 600));
        setSize(new java.awt.Dimension(750, 600));

        jPanel1.setBackground(new java.awt.Color(32, 103, 178));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(719, 30));

        closeBtn.setBackground(new java.awt.Color(32, 103, 178));
        closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/close_screen_20px.png"))); // NOI18N
        closeBtn.setOpaque(true);
        closeBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeBtnMouseMoved(evt);
            }
        });
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeBtnMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NASABAH BARU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel4.setLayout(new java.awt.CardLayout());

        slinde1Panel.setBackground(new java.awt.Color(32, 103, 178));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No KTP");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Lengkap");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tempat Lahir");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal Lahir");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alamat Lengkap");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No Telepon");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jenis Kelamin");

        noKTPTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noKTPTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        namaTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        jKLakiRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jKLakiRB.setForeground(new java.awt.Color(255, 255, 255));
        jKLakiRB.setSelected(true);
        jKLakiRB.setText("Laki - laki");
        jKLakiRB.setOpaque(false);

        jkPerempuanRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jkPerempuanRB.setForeground(new java.awt.Color(255, 255, 255));
        jkPerempuanRB.setText("Perempuan");
        jkPerempuanRB.setOpaque(false);

        tempatLahirTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tempatLahirTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        noTlpTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noTlpTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        alamatTextArea.setColumns(20);
        alamatTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alamatTextArea.setLineWrap(true);
        alamatTextArea.setRows(5);
        alamatTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        alamatTextArea.setOpaque(false);
        jScrollPane1.setViewportView(alamatTextArea);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Saldo awal (Rp)");

        saldoTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saldoTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        saldoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                saldoTextFieldKeyTyped(evt);
            }
        });

        potoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        potoLabel.setForeground(new java.awt.Color(255, 255, 255));
        potoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/user_100px.png"))); // NOI18N
        potoLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        potoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        potoLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        potoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        potoBtn.setBackground(new java.awt.Color(35, 171, 226));
        potoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/cari_30px.png"))); // NOI18N
        potoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        potoBtn.setOpaque(true);
        potoBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                potoBtnMouseMoved(evt);
            }
        });
        potoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potoBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                potoBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                potoBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                potoBtnMouseReleased(evt);
            }
        });

        simpanBtn.setBackground(new java.awt.Color(35, 171, 226));
        simpanBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        simpanBtn.setForeground(new java.awt.Color(255, 255, 255));
        simpanBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simpanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/Save_30px.png"))); // NOI18N
        simpanBtn.setText("SIMPAN");
        simpanBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanBtn.setOpaque(true);
        simpanBtn.setPreferredSize(new java.awt.Dimension(34, 40));
        simpanBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                simpanBtnMouseMoved(evt);
            }
        });
        simpanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                simpanBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                simpanBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                simpanBtnMouseReleased(evt);
            }
        });

        validasiPesanLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        validasiPesanLabel.setForeground(new java.awt.Color(255, 255, 255));
        validasiPesanLabel.setText("*Pesan Validasi");
        validasiPesanLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Catatan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        tanggalLahirDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalLahirDatePropertyChange(evt);
            }
        });

        potoCancleBtn.setBackground(new java.awt.Color(35, 171, 226));
        potoCancleBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potoCancleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/cancle_30px.png"))); // NOI18N
        potoCancleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        potoCancleBtn.setOpaque(true);
        potoCancleBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                potoCancleBtnMouseMoved(evt);
            }
        });
        potoCancleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potoCancleBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                potoCancleBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                potoCancleBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                potoCancleBtnMouseReleased(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Saldo awal minimal Rp 100.000 -;");

        javax.swing.GroupLayout slinde1PanelLayout = new javax.swing.GroupLayout(slinde1Panel);
        slinde1Panel.setLayout(slinde1PanelLayout);
        slinde1PanelLayout.setHorizontalGroup(
            slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slinde1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(slinde1PanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(slinde1PanelLayout.createSequentialGroup()
                        .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tanggalLahirDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, slinde1PanelLayout.createSequentialGroup()
                                .addComponent(jKLakiRB)
                                .addGap(27, 27, 27)
                                .addComponent(jkPerempuanRB))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noKTPTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(tempatLahirTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(noTlpTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(slinde1PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                                .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(slinde1PanelLayout.createSequentialGroup()
                                        .addComponent(potoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(potoCancleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(potoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89))
                            .addGroup(slinde1PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(validasiPesanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(slinde1PanelLayout.createSequentialGroup()
                        .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(slinde1PanelLayout.createSequentialGroup()
                                .addComponent(saldoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(simpanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(slinde1PanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        slinde1PanelLayout.setVerticalGroup(
            slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slinde1PanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(slinde1PanelLayout.createSequentialGroup()
                        .addComponent(noKTPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jKLakiRB)
                            .addComponent(jkPerempuanRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tempatLahirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(slinde1PanelLayout.createSequentialGroup()
                        .addComponent(potoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(potoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(potoCancleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalLahirDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTlpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validasiPesanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(slinde1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(7, 7, 7))
        );

        jPanel4.add(slinde1Panel, "card2");

        slide2Panel.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(32, 103, 178));
        jPanel3.setPreferredSize(new java.awt.Dimension(738, 60));

        printnBtn.setBackground(new java.awt.Color(35, 171, 226));
        printnBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printnBtn.setForeground(new java.awt.Color(255, 255, 255));
        printnBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myBank/resource/icon/Print_30px.png"))); // NOI18N
        printnBtn.setText("PRINT");
        printnBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printnBtn.setOpaque(true);
        printnBtn.setPreferredSize(new java.awt.Dimension(34, 40));
        printnBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                printnBtnMouseMoved(evt);
            }
        });
        printnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printnBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printnBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                printnBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                printnBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(623, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        slide2Panel.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("No Rekening");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("No KTP");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Nama");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Jenis Kelamin");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Tempat / Tanggal Lahir");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Alamat");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Saldo");

        noRekLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noRekLabel.setText(": 12345678");
        noRekLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("DATA NASABAH");

        noKTPLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noKTPLabel.setText(": 12345678");
        noKTPLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        namaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaLabel.setText(": 12345678");
        namaLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jenisKelaminLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jenisKelaminLabel.setText(": 12345678");
        jenisKelaminLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        TTLLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TTLLabel.setText(": 12345678");
        TTLLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        alamatLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alamatLabel.setText(": 12345678");
        alamatLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        saldoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saldoLabel.setText(": 12345678");
        saldoLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        idNasabahLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idNasabahLabel.setText(": 12345678");
        idNasabahLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("ID Nasabah");

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordLabel.setText(": 12345678");
        passwordLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Password");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jenisKelaminLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(noKTPLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(noRekLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(TTLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(alamatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idNasabahLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saldoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noRekLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(noKTPLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jenisKelaminLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TTLLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamatLabel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(saldoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idNasabahLabel)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(jLabel30))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        slide2Panel.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel4.add(slide2Panel, "card3");

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanBtnMouseClicked
        nasabahCtrl.addNasabah(this);
    }//GEN-LAST:event_simpanBtnMouseClicked

    private void potoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMouseClicked
        JFileChooser jfc = new JFileChooser();
        FileFilter pngFilter = new FileNameExtensionFilter("photo (.png)", "png");
        jfc.setAcceptAllFileFilterUsed(false);
        jfc.addChoosableFileFilter(pngFilter);        
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            pathPhoto = jfc.getSelectedFile().toString();
            if (!"".equals(pathPhoto)) {
                pathPhoto = pathPhoto.replace("\\", "/");
                BufferedImage loadImg = photoStyle.loadImage(pathPhoto);
                ImageIcon imageIcon = new ImageIcon(photoStyle.resize(loadImg, potoLabel.getWidth() - 1, potoLabel.getHeight() - 1));
                potoLabel.setIcon(imageIcon);
            }
        }
    }//GEN-LAST:event_potoBtnMouseClicked

    private void simpanBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanBtnMouseExited
        btnStyle.borderMouseExit(simpanBtn);
    }//GEN-LAST:event_simpanBtnMouseExited

    private void simpanBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanBtnMouseMoved
        btnStyle.borderMouseMoved(simpanBtn);
    }//GEN-LAST:event_simpanBtnMouseMoved

    private void simpanBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanBtnMousePressed
        btnStyle.backgroundMousePressed(simpanBtn);
    }//GEN-LAST:event_simpanBtnMousePressed

    private void simpanBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanBtnMouseReleased
        btnStyle.backgroundMouseReleased(simpanBtn);
    }//GEN-LAST:event_simpanBtnMouseReleased

    private void potoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMouseExited
        btnStyle.borderMouseExit(potoBtn);
    }//GEN-LAST:event_potoBtnMouseExited

    private void potoBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMouseMoved
        btnStyle.borderMouseMoved(potoBtn);
    }//GEN-LAST:event_potoBtnMouseMoved

    private void potoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMousePressed
        btnStyle.backgroundMousePressed(potoBtn);
    }//GEN-LAST:event_potoBtnMousePressed

    private void potoBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoBtnMouseReleased
        btnStyle.backgroundMouseReleased(potoBtn);
    }//GEN-LAST:event_potoBtnMouseReleased

    private void tanggalLahirDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalLahirDatePropertyChange
        if (tanggalLahirDate.getDate() != null) {
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            tanggalLahir = simpleDateFormat.format(tanggalLahirDate.getDate());
        }
    }//GEN-LAST:event_tanggalLahirDatePropertyChange

    private void potoCancleBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMouseMoved
        btnStyle.borderMouseMoved(potoCancleBtn);
    }//GEN-LAST:event_potoCancleBtnMouseMoved

    private void potoCancleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMouseClicked
        pathPhoto = "null";
        potoLabel.setIcon(new ImageIcon("src/mybank/resource/icon/user_100px.png"));
    }//GEN-LAST:event_potoCancleBtnMouseClicked

    private void potoCancleBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMouseExited
        btnStyle.borderMouseExit(potoCancleBtn);
    }//GEN-LAST:event_potoCancleBtnMouseExited

    private void potoCancleBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMousePressed
        btnStyle.backgroundMousePressed(potoCancleBtn);
    }//GEN-LAST:event_potoCancleBtnMousePressed

    private void potoCancleBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potoCancleBtnMouseReleased
        btnStyle.backgroundMouseReleased(potoCancleBtn);
    }//GEN-LAST:event_potoCancleBtnMouseReleased

    private void printnBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printnBtnMouseMoved
        btnStyle.borderMouseMoved(printnBtn);
    }//GEN-LAST:event_printnBtnMouseMoved

    private void printnBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printnBtnMouseClicked

    }//GEN-LAST:event_printnBtnMouseClicked

    private void printnBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printnBtnMouseExited
        btnStyle.borderMouseExit(printnBtn);
    }//GEN-LAST:event_printnBtnMouseExited

    private void printnBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printnBtnMousePressed
        btnStyle.backgroundMousePressed(printnBtn);
    }//GEN-LAST:event_printnBtnMousePressed

    private void printnBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printnBtnMouseReleased
        btnStyle.backgroundMouseReleased(printnBtn);
    }//GEN-LAST:event_printnBtnMouseReleased

    private void saldoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saldoTextFieldKeyTyped
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_saldoTextFieldKeyTyped

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        btnStyle.backgroundMouseExit(closeBtn);
    }//GEN-LAST:event_closeBtnMouseExited

    private void closeBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseMoved
        closeBtn.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_closeBtnMouseMoved

    private void closeBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseReleased
        closeBtn.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_closeBtnMouseReleased

    private void closeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMousePressed
        btnStyle.backgroundMousePressed(closeBtn);
    }//GEN-LAST:event_closeBtnMousePressed

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nasabahNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nasabahNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nasabahNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nasabahNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                nasabahNew dialog = new nasabahNew(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TTLLabel;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel idNasabahLabel;
    private javax.swing.JRadioButton jKLakiRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenisKelaminLabel;
    private javax.swing.JRadioButton jkPerempuanRB;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel noKTPLabel;
    private javax.swing.JTextField noKTPTextField;
    private javax.swing.JLabel noRekLabel;
    private javax.swing.JTextField noTlpTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel potoBtn;
    private javax.swing.JLabel potoCancleBtn;
    private javax.swing.JLabel potoLabel;
    private javax.swing.JLabel printnBtn;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JTextField saldoTextField;
    private javax.swing.JLabel simpanBtn;
    private javax.swing.JPanel slide2Panel;
    private javax.swing.JPanel slinde1Panel;
    private com.toedter.calendar.JDateChooser tanggalLahirDate;
    private javax.swing.JTextField tempatLahirTextField;
    private javax.swing.JLabel validasiPesanLabel;
    // End of variables declaration//GEN-END:variables

    private void If(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
